name: Roomism University
favicon: null
layout_spectrum: 0.25530355935916305
typography_spectrum: 0.9951504932250828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5833503319881856
  lightness: 0.9571907131467015
  saturation: 0.18508339556865394
  rhythmicContrast: 0.14489913824945688
purpose: []
